[pytest]
# 测试文件匹配模式
python_files = *_test.py
python_classes = *Test
python_functions = *_test

# 命令行默认选项
addopts =
    -v
    -s
;    -m
    --strict-markers
    --tb=short
    --html=reports/report.html
    --self-contained-html

# 测试目录
testpaths = tests/cases

# 标记定义
markers =
    smoke: 冒烟测试
    regression: 回归测试
    slow: 慢速测试
    functional: 功能测试

    module: 模块测试
    interface: 接口测试
    api: API测试
    ui: UI测试

    ipc: ipc功能测试
    terminal: 终端功能测试

    dmz: dmz 功能测试
